Adicionando o Header e o Footer das páginas
unb-mds/2024-2-Squad06 pull request #50
Opened 2024-12-07 21:03 UTC by TiagoTeixeira-2005

Adição dos arquivos Header e Footer referentes ao front-end do projeto.
Co-authored-by: ArthurGuilher62 <Arthurguilher062@gmail.com>
Co-authored-by: NayraNery127 <nerynayra17@gmail.com>

2024-12-07 21:06 UTC, ArthurGuilher62 approved these changes

2024-12-11 19:06 UTC, Neoprot commented on client/src/App.css
> +  column-gap: 32px;
Evite uso de pxs, use medidas relativas como EM ou REM

2024-12-11 19:22 UTC, Neoprot requested changes
Altere conforme pedido nos comentários, o carrosel não precisa ser alterado agora, para aprovar essa alteração

2024-12-11 19:22 UTC, Neoprot commented on client/src/App.css
> +  font-size: 14px;
Evite uso de pxs, use medidas relativas como EM ou REM, assim faz com que a tela fique melhor independente do dispositivo usado
[leitura](https://dev.to/lixeletto/entendendo-unidades-css-e-quando-utiliza-las-3ecc)

2024-12-11 19:22 UTC, Neoprot commented on client/src/App.css
> +  font-weight: bold;  /* Altere para 'bold' ou '700' para deixar o texto em negrito */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/App.css
> +  max-width: 90px;
Evite uso de pxs, use medidas relativas como EM ou REM, assim faz com que a tela fique melhor independente do dispositivo usado
[leitura](https://dev.to/lixeletto/entendendo-unidades-css-e-quando-utiliza-las-3ecc)

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/BarraPesquisa/BarraPesquisa.css
> +      background-color: #112632; /* Cor do fundo no hover */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/BarraPesquisa/BarraPesquisa.tsx
Componente no local errado, por se tratar de um componente que fica apenas na home, deve ser movido para dentro da pasta de componentes da home

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/CardGastos/CardGastos.css
> +    max-width: 30%; /* A largura agora é 30% da tela */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/CardGastos/CardGastos.css
> +    max-height: 25%; /* A altura agora é 25% da tela */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/Footer/Footer.css
> +  column-gap: 8.5rem;  /*Aumento do Gap*/
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/Header/Header.css
> +  column-gap: 8.5rem;  /*Aumento do Gap*/
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/Footer/Footer.css
> +  border-bottom: 3px solid white;
Evite uso de pxs, use medidas relativas como EM ou REM, assim faz com que a tela fique melhor independente do dispositivo usado
[leitura](https://dev.to/lixeletto/entendendo-unidades-css-e-quando-utiliza-las-3ecc)

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/Footer/Footer.css
> +  top: 1.25rem;  /* Mover a linha para baixo, equivalente a 20px (1.25rem) */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/Footer/Footer.css
> +  position: absolute;  /* Coloca a linha fora do fluxo normal de layout */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/Header/Header.css
> +  font-family: 'Season_Prime', sans-serif;
Vi a declaração dessa fonte várias vezes, talvez não fosse melhor alocar ela em uma variável, depois chamar apenas a variável em cada um dos arquivos?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* contêiner do carrossel */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* Estilo para as setas de navegação */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* Estilo para o contêiner da imagem e texto */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* Barra inferior */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* Estilo para o texto título sobre a imagem */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* imagem */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +  font-size: 1vw;  /* Tamanho da fonte adaptativo */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +/* Corpo do texto */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/components/carrossel/carroselStyle.css
> +  opacity: 1; /* Controla a opacidade da sobreposição */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/pages/Home/Home.tsx
> +      <Carrossel/>
Carrosel é geralmente um componente que queremos poder usa-lo em diversas situações e apenas passar para ele os elementos que deve-se ter nele, não seria melhor uma refatoração? Para fazer com que esse carrosel possa ser utilizado em outras situações?

2024-12-11 19:22 UTC, Neoprot commented on client/src/pages/SobreNos/SobreNos.css
> +    padding: 0 1.25rem;          /* Substituído 20px por 1.25rem */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/pages/SobreNos/SobreNos.css
> +    font-size: 1.2rem;            /* Permaneceu como está, já está em rem */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/pages/SobreNos/SobreNos.css
> +    max-width: 100%;              /* Garante que a imagem não ultrapasse o tamanho do contêiner */
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/pages/SobreNos/SobreNos.css
> +    width: 100%;
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:22 UTC, Neoprot commented on client/src/pages/SobreNos/SobreNos.css
> +  }
Remova comentários desnecessários, feito com CHATGPT?

2024-12-11 19:23 UTC, Neoprot commented
@TiagoTeixeira-2005 @ArthurGuilher62 @NayraNery127

2024-12-12 22:37 UTC, Neoprot requested changes

2024-12-12 22:37 UTC, Neoprot commented on client/src/components/Footer/Footer.css
> +@media (max-width: 53.75rem) {
Media Não se usa REM, devido a ser a resolução da tela e não um elemento em si

2024-12-12 23:13 UTC, Neoprot approved these changes

2024-12-12 23:13 UTC, merged